version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8765:8765"
    networks:
      - postgres-network
    restart: always


  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: server
      POSTGRES_USER: server
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: always


volumes:
  postgres_data:
    driver: local

networks:
  postgres-network:
    driver: bridge