spring:
  application:
    name: bank-card-management

#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    contexts: development


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/server
    username: server
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8765

security:
  jwt:
    minutes:
      live: 720

    key: F2544219AE74B211A443975496C1B0B0F9CEDF6BDEBC0687A889693F5279D5FB

  masked:
    secret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
    algorithm: AES
